import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { supabase } from '../lib/supabaseClient.js'
import { generatePlan } from '../lib/generatePlan.js'

export default function NewPlan() {
  const [subject, setSubject] = useState('')
  const [topics, setTopics] = useState('')
  const [deadline, setDeadline] = useState('')
  const [hours, setHours] = useState(2)
  const [preview, setPreview] = useState(null)
  const [source, setSource] = useState('')
  const [busy, setBusy] = useState(false)
  const navigate = useNavigate()

  async function onGenerate(e) {
    e.preventDefault()
    setBusy(true)
    const input = { subject, topics, deadline, hoursPerDay: Number(hours) }
    const { tasks, source } = await generatePlan(input)
    setPreview(tasks)
    setSource(source)
    setBusy(false)
  }

  async function onSave() {
    const { data: session } = await supabase.auth.getSession()
    const user = session.session?.user
    if (!user) return
    const { data, error } = await supabase
      .from('study_plans')
      .insert({
        user_id: user.id,
        subject,
        topics,
        deadline,
        hours_per_day: Number(hours),
        plan_json: preview
      })
      .select()
      .single()
    if (!error) navigate(`/plan/${data.id}`)
  }

  return (
    <main className="mx-auto max-w-2xl px-4 py-8">
      <h1 className="text-2xl font-bold">New study plan</h1>
      <form onSubmit={onGenerate} className="mt-6 space-y-4">
        <input
          required
          placeholder="Subject, e.g. Biology"
          value={subject}
          onChange={(e) => setSubject(e.target.value)}
          className="w-full rounded border px-3 py-2"
        />
        <textarea
          required
          placeholder="Topics, separated by commas or new lines"
          value={topics}
          onChange={(e) => setTopics(e.target.value)}
          rows={4}
          className="w-full rounded border px-3 py-2"
        />
        <div className="grid grid-cols-2 gap-4">
          <input
            required
            type="date"
            value={deadline}
            onChange={(e) => setDeadline(e.target.value)}
            className="rounded border px-3 py-2"
          />
          <input
            required
            type="number"
            min={1}
            max={12}
            value={hours}
            onChange={(e) => setHours(e.target.value)}
            className="rounded border px-3 py-2"
          />
        </div>
        <button disabled={busy} className="w-full rounded bg-indigo-600 py-2 text-white disabled:opacity-50">
          {busy ? 'Generating...' : 'Generate plan'}
        </button>
      </form>

      {preview && (
        <div className="mt-8 rounded border bg-white p-5">
          <p className="text-sm text-slate-500">
            {source === 'ai' ? 'Generated by AI' : 'Generated offline'} — {preview.length} tasks
          </p>
          <ul className="mt-3 space-y-2">
            {preview.map((t) => (
              <li key={t.id} className="flex justify-between text-sm">
                <span>{t.title}</span>
                <span className="text-slate-500">{t.date} · {t.duration_min}m</span>
              </li>
            ))}
          </ul>
          <button onClick={onSave} className="mt-4 w-full rounded bg-green-600 py-2 text-white">
            Save plan
          </button>
        </div>
      )}
    </main>
  )
}
